/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/forms/FormCehckBox copy.vue')['default']
    ElementsButton: typeof import('./components/elements/Button.vue')['default']
    ElementsLabel: typeof import('./components/elements/Label.vue')['default']
    FormsFormCehckBox: typeof import('./components/forms/FormCehckBox.vue')['default']
    'FormsFormCehckBox.stories': typeof import('./components/forms/FormCehckBox.stories.vue')['default']
    FormsFormInput: typeof import('./components/forms/FormInput.vue')['default']
    FormsFormRadio: typeof import('./components/forms/FormRadio.vue')['default']
    FormsFormTextarea: typeof import('./components/forms/FormTextarea.vue')['default']
    FormsFormTitle: typeof import('./components/forms/FormTitle.vue')['default']
    FormsLabelsLeft: typeof import('./components/forms/LabelsLeft.vue')['default']
    FormsStacked: typeof import('./components/forms/Stacked.vue')['default']
    FormsTowColumn: typeof import('./components/forms/TowColumn.vue')['default']
    FormsTowColumnCards: typeof import('./components/forms/TowColumnCards.vue')['default']
    HeadingsHeadingMetaActions: typeof import('./components/headings/HeadingMetaActions.vue')['default']
    MapMap: typeof import('./components/map/Map.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
