import React from "react";
import PropTypes from "prop-types";

export const Typography = ({
  family,
  size,
  thick,
  children,
  className,
  smoothing,
  style,
  weight,
  variantNumeric,
  letterSpacing,
  lineClamp,
  lineHeight,
  listStylePosition,
  listStyleType,
  textAlign,
  textColor,
  textThick,
  decoration,
  decorationColor,
  decorationThick,
  underlineOffset,
  transform,
  overflow,
  indent,
  verticalAlign,
  ...props
}) => {
  return (
    <div
      className={[
        "w-full",
        `${family ?? ""}`,
        `${size ?? ""}`,
        `${className ?? ""}`,
        `${smoothing ?? ""}`,
        `${style ?? ""}`,
        `${weight ?? ""}`,
        `${variantNumeric ?? ""}`,
        `${letterSpacing ?? ""}`,
        `${lineClamp ?? ""}`,
        `${lineHeight ?? ""}`,
        `${listStylePosition ?? ""}`,
        `${listStyleType ?? ""}`,
        `${textAlign ?? ""}`,
        `${textColor ? "text-" : ""}${textColor ?? ""}${textThick ?? ""}`,
        `${decoration ?? ""}`,
        `${decorationColor ? "decoration-" : ""}${decorationColor ?? ""}${decorationThick ?? ""}`,
        `${underlineOffset ?? ""}`,
        `${transform ?? ""}`,
        `${overflow ?? ""}`,
        `${indent ?? ""}`,
        `${verticalAlign ?? ""}`,
      ].join(" ")}
    >
      {children}
    </div>
  );
};

Typography.propTypes = {
  family: PropTypes.oneOf(["", "font-sans", "font-serif", "font-mono"]),
  size: PropTypes.oneOf([
    "",
    "text-xs",
    "text-sm",
    "text-base",
    "text-lg",
    "text-xl",
    "text-2xl",
    "text-3xl",
    "text-4xl",
    "text-5xl",
    "text-6xl",
    "text-7xl",
    "text-8xl",
    "text-9xl",
  ]),
  smoothing: PropTypes.oneOf(["", "antialiased", "subpixel-antialiased"]),
  style: PropTypes.oneOf(["", "italic", "not-italic"]),
  weight: PropTypes.oneOf([
    "",
    "font-thin",
    "font-extralight",
    "font-light",
    "font-normal",
    "font-medium",
    "font-semibold",
    "font-bold",
    "font-extrabold",
    "font-black",
  ]),
  variantNumeric: PropTypes.oneOf([
    "",
    "normal-nums",
    "ordinal",
    "slashed-zero",
    "lining-nums",
    "oldstyle-nums",
    "proportional-nums",
    "tabular-nums",
    "diagonal-fractions",
    "stacked-fractions",
  ]),
  letterSpacing: PropTypes.oneOf([
    "",
    "tracking-tighter",
    "tracking-tight",
    "tracking-normal",
    "tracking-wide",
    "tracking-wider",
    "tracking-widest",
  ]),
  lineClamp: PropTypes.oneOf([
    "",
    "line-clamp-1",
    "line-clamp-2",
    "line-clamp-3",
    "line-clamp-4",
    "line-clamp-5",
    "line-clamp-6",
    "line-clamp-none",
  ]),
  lineHeight: PropTypes.oneOf([
    "",
    "leading-3",
    "leading-4",
    "leading-5",
    "leading-6",
    "leading-7",
    "leading-8",
    "leading-9",
    "leading-10",
    "leading-none",
    "leading-tight",
    "leading-snug",
    "leading-normal",
    "leading-relaxed",
    "leading-loose",
  ]),
  listStylePosition: PropTypes.oneOf([
    "",
    "list-inside",
    "list-outside",
  ]),
  listStyleType: PropTypes.oneOf([
    "",
    "list-none",
    "list-disc",
    "list-decimal",
  ]),
  textAlign: PropTypes.oneOf([
    "",
    "text-left",
    "text-center",
    "text-right",
    "text-justify",
    "text-start",
    "text-end",
  ]),
  textColor: PropTypes.oneOf([
    "",
    "inherit",
    "current",
    "transparent",
    "black",
    "white",
    "slate",
    "gray",
    "zinc",
    "neutral",
    "stone",
    "red",
    "orange",
    "amber",
    "yellow",
    "lime",
    "green",
    "emerald",
    "teal",
    "cyan",
    "sky",
    "blue",
    "indigo",
    "violet",
    "purple",
    "fuchsia",
    "pink",
    "rose",
  ]),
  textThick: PropTypes.oneOf([
    "",
    "-50",
    "-100",
    "-200",
    "-300",
    "-400",
    "-500",
    "-600",
    "-700",
    "-800",
    "-900",
    "-950",
  ]),
  decoration: PropTypes.oneOf([
    "",
    "underline",
    "overline",
    "line-through",
    "no-underline",
  ]),
  decorationColor: PropTypes.oneOf([
    "",
    "inherit",
    "current",
    "transparent",
    "black",
    "white",
    "slate",
    "gray",
    "zinc",
    "neutral",
    "stone",
    "red",
    "orange",
    "amber",
    "yellow",
    "lime",
    "green",
    "emerald",
    "teal",
    "cyan",
    "sky",
    "blue",
    "indigo",
    "violet",
    "purple",
    "fuchsia",
    "pink",
    "rose",
  ]),
  decorationThick: PropTypes.oneOf([
    "",
    "-50",
    "-100",
    "-200",
    "-300",
    "-400",
    "-500",
    "-600",
    "-700",
    "-800",
    "-900",
    "-950",
  ]),
  underlineOffset: PropTypes.oneOf([
    "",
    "underline-offset-auto",
    "underline-offset-0",
    "underline-offset-1",
    "underline-offset-2",
    "underline-offset-4",
    "underline-offset-8",
  ]),
  transform: PropTypes.oneOf([
    "",
    "uppercase",
    "lowercase",
    "capitalize",
    "normal-case",
  ]),
  overflow: PropTypes.oneOf([
    "",
    "truncate",
    "text-ellipsis",
    "text-clip",
    "normal-case",
  ]),
  indent: PropTypes.oneOf([
    "",
    "indent-0",
    "indent-px",
    "indent-0.5",
    "indent-1",
    "indent-1.5",
    "indent-2",
    "indent-2.5",
    "indent-3",
    "indent-3.5",
    "indent-4",
    "indent-5",
    "indent-6",
    "indent-7",
    "indent-8",
    "indent-9",
    "indent-10",
    "indent-11",
    "indent-12",
    "indent-14",
    "indent-16",
    "indent-20",
    "indent-24",
    "indent-28",
    "indent-32",
    "indent-36",
    "indent-40",
    "indent-44",
    "indent-48",
    "indent-52",
    "indent-56",
    "indent-60",
    "indent-64",
    "indent-72",
    "indent-80",
    "indent-96",
  ]),
  verticalAlign: PropTypes.oneOf([
    "",
    "align-baseline",
    "align-top",
    "align-middle",
    "align-bottom",
    "align-text-top",
    "align-text-bottom",
    "align-sub",
    "align-super",
  ]),
};

Typography.defaultProps = {
  family: "",
  size: "",
  smoothing: "",
  textColor: "",
  textThick: "",
};
