import React from "react";
import PropTypes from "prop-types";

export const Typography = ({
  family,
  size,
  thick,
  children,
  className,
  smoothing,
  style,
  weight,
  variantNumeric,
  letterSpacing,
  lineClamp,
  lineHeight,
  listStylePosition,
  listStyleType,
  textAlign,
  textColor,
  textThick,
  ...props
}) => {
  return (
    <div
      className={[
        "w-full",
        "h-full",
        `${family}`,
        `${size}`,
        `${className}`,
        `${smoothing}`,
        `${style}`,
        `${weight}`,
        `${variantNumeric}`,
        `${letterSpacing}`,
        `${lineClamp}`,
        `${lineHeight}`,
        `${listStylePosition}`,
        `${listStyleType}`,
        `${textAlign}`,
        `text-${textColor}${textThick}`,
      ].join(" ")}
    >
      {children}
    </div>
  );
};

Typography.propTypes = {
  family: PropTypes.oneOf(["", "font-sans", "font-serif", "font-mono"]),
  size: PropTypes.oneOf([
    "",
    "text-xs",
    "text-sm",
    "text-base",
    "text-lg",
    "text-xl",
    "text-2xl",
    "text-3xl",
    "text-4xl",
    "text-5xl",
    "text-6xl",
    "text-7xl",
    "text-8xl",
    "text-9xl",
  ]),
  smoothing: PropTypes.oneOf(["", "antialiased", "subpixel-antialiased"]),
  style: PropTypes.oneOf(["", "italic", "not-italic"]),
  weight: PropTypes.oneOf([
    "",
    "font-thin",
    "font-extralight",
    "font-light",
    "font-normal",
    "font-medium",
    "font-semibold",
    "font-bold",
    "font-extrabold",
    "font-black",
  ]),
  variantNumeric: PropTypes.oneOf([
    "",
    "normal-nums",
    "ordinal",
    "slashed-zero",
    "lining-nums",
    "oldstyle-nums",
    "proportional-nums",
    "tabular-nums",
    "diagonal-fractions",
    "stacked-fractions",
  ]),
  letterSpacing: PropTypes.oneOf([
    "",
    "tracking-tighter",
    "tracking-tight",
    "tracking-normal",
    "tracking-wide",
    "tracking-wider",
    "tracking-widest",
  ]),
  lineClamp: PropTypes.oneOf([
    "",
    "line-clamp-1",
    "line-clamp-2",
    "line-clamp-3",
    "line-clamp-4",
    "line-clamp-5",
    "line-clamp-6",
    "line-clamp-none",
  ]),
  lineHeight: PropTypes.oneOf([
    "",
    "leading-3",
    "leading-4",
    "leading-5",
    "leading-6",
    "leading-7",
    "leading-8",
    "leading-9",
    "leading-10",
    "leading-none",
    "leading-tight",
    "leading-snug",
    "leading-normal",
    "leading-relaxed",
    "leading-loose",
  ]),
  listStylePosition: PropTypes.oneOf([
    "",
    "list-inside",
    "list-outside",
  ]),
  listStyleType: PropTypes.oneOf([
    "",
    "list-none",
    "list-disc",
    "list-decimal",
  ]),
  textAlign: PropTypes.oneOf([
    "",
    "text-left",
    "text-center",
    "text-right",
    "text-justify",
    "text-start",
    "text-end",
  ]),
  textColor: PropTypes.oneOf([
    "",
    "inherit",
    "current",
    "transparent",
    "black",
    "white",
    "slate",
    "gray",
    "zinc",
    "neutral",
    "stone",
    "red",
    "orange",
    "amber",
    "yellow",
    "lime",
    "green",
    "emerald",
    "teal",
    "cyan",
    "sky",
    "blue",
    "indigo",
    "violet",
    "purple",
    "fuchsia",
    "pink",
    "rose",
  ]),
  textThick: PropTypes.oneOf([
    "",
    "-50",
    "-100",
    "-200",
    "-300",
    "-400",
    "-500",
    "-600",
    "-700",
    "-800",
    "-900",
    "-950",
  ]),
};

Typography.defaultProps = {
  family: "",
  size: "",
  smoothing: "",
  textColor: "",
  textThick: "",
};
